server:
  port: 6001

spring:
  application:
    name: omega-sc-demo-rest
  redis:
    host: 127.0.0.1
    port: 6379
  cache:
    type: redis
  main:
    allow-bean-definition-overriding: true

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: omega-demo
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  health:
    rabbit:
      enabled: false
    redis:
      enabled: false


